apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docker-registry.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "docker-registry.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "docker-registry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "docker-registry.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: registry
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
          envFrom: []
          volumeMounts:
            # Registry configuration
            - name: config
              mountPath: /etc/docker/registry
              readOnly: true
            # Image storage
            - name: data
              mountPath: /var/lib/registry
            {{- if .Values.auth.enabled }}
            # Authentication htpasswd
            - name: auth
              mountPath: /auth
              readOnly: true
            {{- end }}
          {{- with .Values.healthCheck.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.healthCheck.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "docker-registry.fullname" . }}-config
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "docker-registry.fullname" . }}-data
        {{- else }}
        - name: data
          emptyDir: {}
        {{- end }}
        {{- if .Values.auth.enabled }}
        - name: auth
          secret:
            secretName: {{ include "docker-registry.fullname" . }}-auth
        {{- end }}