{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docker-registry.fullname" . }}-auth
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "docker-registry.labels" . | nindent 4 }}
type: Opaque
data:
  htpasswd: {{ .Values.auth.htpasswd }}
{{- end }}